"""
Admin Pydantic Schemas (DTOs)
==============================
Strict validation layer between the API and the database for all
admin-facing operations (room management + manual booking creation).

Request schemas  (no `id`)  → validate incoming POST body
Response schemas (with `id`) → shape outgoing JSON, read from ORM objects
"""

from pydantic import BaseModel


# ---------------------------------------------------------------------------
# REQUEST SCHEMAS  (incoming data — id is generated by the DB, never sent in)
# ---------------------------------------------------------------------------


class RoomCreate(BaseModel):
    """
    Body for POST /api/admin/rooms
    Creates a new room in the system.
    """

    room_number: str
    type: str
    price_per_night: float


class ManualBookingCreate(BaseModel):
    """
    Body for POST /api/admin/bookings/manual
    Admin creates a booking on behalf of a guest (no auth required for guest).
    Dates must be strings in YYYY-MM-DD format.
    """

    guest_name: str
    guest_email: str | None = None
    guest_phone: str | None = None
    room_id: int
    start_date: str   # YYYY-MM-DD
    end_date: str     # YYYY-MM-DD


# ---------------------------------------------------------------------------
# RESPONSE SCHEMAS  (outgoing data — id is included, read directly from ORM)
# ---------------------------------------------------------------------------


class RoomResponse(BaseModel):
    """
    Response for POST /api/admin/rooms
    Returns the created room including its database-generated id.
    """

    id: int
    room_number: str
    type: str
    price_per_night: float

    # Pydantic v2: allows reading directly from SQLAlchemy model instances
    model_config = {"from_attributes": True}


class BookingResponse(BaseModel):
    """
    Response for:
    - POST /api/admin/bookings/manual  (created booking)
    - GET  /api/admin/bookings         (list of all bookings)
    - PATCH /api/admin/bookings/{id}/status
    """

    id: int
    guest_name: str
    guest_email: str | None = None
    guest_phone: str | None = None
    room_id: int
    start_date: str
    end_date: str
    status: str

    # Pydantic v2: allows reading directly from SQLAlchemy model instances
    model_config = {"from_attributes": True}


class BookingStatusUpdate(BaseModel):
    """Body for PATCH /api/admin/bookings/{id}/status"""
    status: str  # "pending" | "confirmed" | "cancelled" | "completed"


class BookingUpdate(BaseModel):
    """Body for PATCH /api/admin/bookings/{id} — edit booking details."""
    guest_name: str | None = None
    guest_email: str | None = None
    guest_phone: str | None = None
    start_date: str | None = None   # YYYY-MM-DD
    end_date: str | None = None     # YYYY-MM-DD


class RoomUpdate(BaseModel):
    """Body for PATCH /api/admin/rooms/{id} — edit room details."""
    room_number: str | None = None
    type: str | None = None
    price_per_night: float | None = None
